# Generated by Django 5.2.4 on 2025-08-11 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('first_air_date', models.DateTimeField(blank=True, null=True)),
                ('watch_date', models.DateField(blank=True, null=True)),
                ('number', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=500)),
                ('poster_url', models.CharField(blank=True, max_length=500, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('picture_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('number', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('poster_url', models.CharField(blank=True, max_length=500, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('watch_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='pwa.genre')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_credit_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('character', models.CharField(blank=True, max_length=200)),
                ('job', models.CharField(blank=True, max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwa.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwa.person')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, max_length=200)),
                ('job', models.CharField(blank=True, max_length=200)),
                ('tmdb_credit_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwa.episode')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwa.person')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='pwa.season'),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('poster_url', models.CharField(blank=True, max_length=500, null=True)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='shows', to='pwa.genre')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='pwa.show'),
        ),
    ]
